User.create!(name: 'a', email: 'test1@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')
User.create!(name: 'b', email: 'test2@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')
User.create!(name: 'c', email: 'test3@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')
User.create!(name: 'd', email: 'test4@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')
User.create!(name: 'e', email: 'test5@gmail.com', password: 'aaaaaa', password_confirmation: 'aaaaaa')

Memo.create!(user_id: 1, content: 'あいうえお')
Memo.create!(user_id: 2, content: 'かきくけこ')
Memo.create!(user_id: 3, content: 'さしすせそ')
Memo.create!(user_id: 4, content: 'たちつてと')
Memo.create!(user_id: 5, content: 'なにぬねの')
